# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Tidusvn05's Resume
subtitle: "I will try even if I don't have a chance!"
description: 'aaaa'
keywords:
author: Tidusvn05
language: en
timezone: 'Asia/Ho_Chi_Minh'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://localhost:4000
root: '/resume/'
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-crisp-minimal-theme

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

resume:
  name: Tran Tan Dat
  jobtitle: I will try even if I don't have a chance!
  jobtitle2: All things that project need, I will trying!
  contact:
    - icon: fa-envelope
      text: tidusvn05@gmail.com
    - icon: fa-phone-square
      text: +84933731173
    # - icon: fa-globe
    #   text: your-website.com
    #   link: https://tidusvn05.github.io/resume
    - icon: fa-github
      text: Github
      link: https://github.com/tidusvn05
  
  skills:
    - title: PHP
      items: Laravel Framework, Lumen API Framework, Codeigniter, Zend Framework,...
    - title: Nodejs
      items: Express webframework, botframework v3,LINE Bottender,..
    - title: Frontend
      items: Basic HTML5/CSS3 and CSS Frameworks, Nuxtjs framework, Basic ReactJs, ReactNative,...
  experience:
    - title: Freelancer and Startup with 123maizo
      duration: March 2009 - Jul 2010
      description: 'I and my friend develop a website, platform connect seller and buyer.\
      <br/>ssss\
      <br/>ssss'
    - title: PHP Developer
      duration: March 2010 - 
      company: JV-IT., JSC
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    - title: Job Title 2
      duration: Apr 2013 - Mar 2016
      company: Your 2nd, Inc.
      description: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    - title: Job Title 3
      duration: Dec 2021 - Mar 2012
      company: JV-IT Techs
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  projects:
    - name: 123Group with 123Maizo, 123Tivi, 123Softwave
      description: 
      contribution: Co-Founder.
    - name: Project Name 1
      description: Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      contribution: Contributor.
    - name: Project Name 2
      description: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      contribution: Creator and maintainer.
  education:
    - university: Nong Lam University
      duration: Jul 2004 - Dec 2009
      location: Ho Chi Minh City
      major: Geographic Information System with Java.
  languages:
    - name: English
      proficiency: Enough for technical research like Reading, Writing. Bad for Listening, Speaking.
    - name: Vietnamese
      proficiency: Native