<footer style="line-height: 1.5rem;">
  Theme ported from Jekyll to Hexo with <i class="fa fa-heart aria-hidden="true></i> by <a href="https://github.com/crispgm/resume">David Zhang</a>  <span class="print">( <a href="javascript:window.print()">PDF</a> )</span>
  <br/><span>Hosted by Github Pages</span>
  <br/><span>Developed by Tidusvn05 using Hexo framework (<a href="https://github.com/tidusvn05/resume">Sourcecode</a>)</span>
  <br/><span>Deployed Automation by Github Actions</span>
  </p>
</footer>
